/*
    Aenigma - Federated messaging system
    Copyright © 2023-2026 Romulus-Emanuel Ruja <romulus.ruja@aenigma.ro>

    This file is part of Aenigma project.

    Aenigma is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Aenigma is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Aenigma.  If not, see <https://www.gnu.org/licenses/>.
*/

using System.Runtime.InteropServices;
using System.Text;
using Enigma5.App.Common.Utils;
using Enigma5.Crypto;
using Enigma5.Tests.Base;

// Writes Enigma5.Tests.Base/TestOnions.cs: onions for the fixed test keys, which the tests use as stored data.
// A node cannot build onions, so this tool calls the native library itself. Run it again only when the
// onion format or the test keys change:
//
//     dotnet run --project Enigma5.Tests.DataGenerator > Enigma5.Tests.Base/TestOnions.cs
//
// Sealing is randomized: every run gives other text for the same content.

NativeLibrary.SetDllImportResolver(typeof(Sealer).Assembly, (name, _, _) => NativeLibrary.Load(RuntimeHelpers.ResolveNativeLibraryPath(name) ?? name));

// Node A has key 1, node B has key 2, and the client that receives the messages has key 3.
var nodeA = TestKeys.PublicKey1;
var nodeB = TestKeys.PublicKey2;
var client = TestKeys.PublicKey3;

var output = new StringBuilder();
output.Append(File.ReadAllText(Path.Combine(AppContext.BaseDirectory, "header.txt")));
output.AppendLine("namespace Enigma5.Tests.Base;");
output.AppendLine();
output.AppendLine("// Generated by Enigma5.Tests.DataGenerator; do not edit. Node A has TestKeys key 1, node B key 2, the client key 3.");
output.AppendLine("public static class TestOnions");
output.AppendLine("{");
Write("ForClientThroughA1", "Sent to node A, which finds the client as destination. Content: \"message 1\".", Sealer.Seal("message 1", client, nodeA));
Write("ForClientThroughA2", "As ForClientThroughA1, with the content \"message 2\".", Sealer.Seal("message 2", client, nodeA));
Write("ForClientThroughA3", "As ForClientThroughA1, with the content \"message 3\".", Sealer.Seal("message 3", client, nodeA));
Write("ForClientThroughAThenB", "Sent to node A, which finds node B as next hop; node B finds the client. Content: \"from A to B\".", Sealer.Seal("from A to B", client, nodeA, nodeB));
Write("ForClientThroughBThenA", "Sent to node B, which finds node A as next hop; node A finds the client. Content: \"from B to A\".", Sealer.Seal("from B to A", client, nodeB, nodeA));
Write("ForClientThroughB", "Sent to node B. Node A cannot open it.", Sealer.Seal("message for B", client, nodeB));
Write("LargeForClientThroughA", "Sent to node A; close to the largest size a node accepts (16384 characters).", Sealer.Seal(new string('x', 11900), client, nodeA));
output.AppendLine("}");
Console.Write(output.ToString());

void Write(string name, string comment, string onion)
{
    output.AppendLine($"    // {comment} {onion.Length} characters.");
    output.AppendLine($"    public const string {name} =");
    output.AppendLine($"        \"{onion}\";");
    output.AppendLine();
}

internal static class Sealer
{
    [DllImport("libaenigma.so", CharSet = CharSet.Ansi)]
    private static extern IntPtr SealOnion([In] byte[] plaintext, uint plaintextLength, [In] string[] keys, [In] string[] addresses, uint count, out int outputLength);

    // The onion for a content that reaches the recipient through the given nodes, in the order of travel.
    public static string Seal(string content, string recipient, params string[] path)
    {
        var plaintext = Encoding.UTF8.GetBytes(content);
        // The library takes the layers from the inside out: the key of each node, and the address that node will find.
        string[] keys = [.. path.Reverse()];
        string[] addresses = [.. new[] { recipient }.Concat(path.Reverse().Take(path.Length - 1)).Select(CertificateHelper.GetHexAddressFromPublicKey)];
        var buffer = SealOnion(plaintext, (uint)plaintext.Length, keys, addresses, (uint)keys.Length, out var length);
        if (buffer == IntPtr.Zero || length <= 0)
        {
            throw new InvalidOperationException("The native library could not seal the onion.");
        }
        // The buffer belongs to the native library and is not released: this tool ends right after.
        var onion = new byte[length];
        Marshal.Copy(buffer, onion, 0, length);
        return Convert.ToBase64String(onion);
    }
}
