Vagrant.configure("2") do |config|
  config.vm.box     = "m3sserschmitt/aenigma5"
  config.vm.box_url = "file://#{File.expand_path('aenigma-virtualbox.box', __dir__)}"
  config.vm.define  "aenigma5"

  config.vm.provider "virtualbox" do |vb|
    vb.name   = "aenigma5"
    vb.memory = 2048
    vb.cpus   = 2
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true
end
