#!/bin/bash

set -e

APP_NAME="aenigma"
SERVICE_USER=$APP_NAME
SERVICE_NAME=$APP_NAME
SERVICE_FILE="/etc/systemd/system/$SERVICE_NAME.service"

case "$1" in
  remove)
    sudo systemctl stop "$SERVICE_NAME"
    sudo systemctl disable "$SERVICE_NAME"
    ;;

  purge)
    sudo rm "$SERVICE_FILE"
    sudo deluser --force --remove-home "$SERVICE_USER"
    ;;
esac
