Vagrant.configure("2") do |config|
  config.vm.box     = "m3sserschmitt/aenigma5"
  config.vm.box_url = "file://#{File.expand_path('aenigma-qemu.box', __dir__)}"
  config.vm.define  "aenigma5"

  config.vm.provider "libvirt" do |lv|
    lv.default_prefix = ""
    lv.memory = 2048
    lv.cpus   = 2
  end

  config.vm.synced_folder ".", "/vagrant", disabled: true
end
